apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: kueue-test
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kueue.x-k8s.io/queue-name: my-local-queue     # Label is important for kueue to look at the workload
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 2
              memory: 3Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: kueue-test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
